"""Phase 2 Agent State definition.

All data shared between LangGraph nodes lives here.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any

from agent.config import MAX_PLAN_VERIFY_LOOPS, MAX_QUERY_TOOL_CALLS, MAX_TOTAL_TOOL_CALLS


@dataclass
class IntakeFacts:
    """Entities extracted from user query by the intake node."""
    intent: str = "troubleshoot"  # troubleshoot | recheck | summary | clarify | chitchat
    trace_id: str | None = None
    trace_ids: list[str] = field(default_factory=list)
    api_key_prefix: str | None = None
    username: str | None = None
    model: str | None = None
    provider: str | None = None
    time_start: str | None = None
    time_end: str | None = None
    error_keywords: list[str] = field(default_factory=list)
    raw_query: str = ""


@dataclass
class Evidence:
    """Single piece of evidence collected by the executor.

    truncated 语义说明：
    - truncated: 单条记录内容被裁短（长堆栈/长响应头尾保留），无法通过继续查询恢复
    - hit_log_limit: 查询结果触及 limit 上限，可能还有更多记录可查
    """
    tool: str
    args: dict[str, Any]
    result: str
    result_size: int = 0
    truncated: bool = False        # 内容裁短（不可恢复）
    hit_log_limit: bool = False    # 触及查询上限（可继续查询获取更多）
    latency_ms: int = 0
    summary: str = ""
    trace_id: str | None = None


@dataclass
class AgentState:
    """Root state object passed through all LangGraph nodes."""
    thread_id: str = ""
    user_query: str = ""
    facts: IntakeFacts = field(default_factory=IntakeFacts)
    skills: list[str] = field(default_factory=list)  # e.g. ["S02", "S07"]
    plan: list[dict[str, Any]] = field(default_factory=list)  # current tool plan
    evidence: list[Evidence] = field(default_factory=list)  # accumulated evidence
    accumulator: dict[str, list[Any]] = field(default_factory=dict)  # paginated aggregation
    executed_hashes: set[str] = field(default_factory=set)  # dedup: hash(tool+args)
    iterations: int = 0
    report: str = ""
    prior_report_summary: str = ""  # 上一轮报告摘要，仅用于同 trace/追问的 planner context
    memory_summary_mode: bool = False  # 总结/对比类追问，只使用短时报告记忆，不索引 history
    investigation_mode: str = "new"  # new | summary_only | reuse_session
    global_plan: str = ""  # high-level investigation plan generated by planner on first iteration
    session_memory: Any | None = None  # 当前 chat session 的结构化记忆，用于 planner 分层上下文
    query_tool_calls: int = 0  # 当前用户问题内实际执行的工具调用数，不包含历史 evidence / verifier hint

    # Control flow (from config)
    MAX_PLAN_VERIFY_LOOPS: int = MAX_PLAN_VERIFY_LOOPS
    MAX_TOTAL_TOOL_CALLS: int = MAX_TOTAL_TOOL_CALLS
    MAX_QUERY_TOOL_CALLS: int = MAX_QUERY_TOOL_CALLS

    @property
    def total_tool_calls(self) -> int:
        return len(self.evidence)

    @property
    def can_call_more_tools(self) -> bool:
        return (
            self.total_tool_calls < self.MAX_TOTAL_TOOL_CALLS
            and self.query_tool_calls < self.MAX_QUERY_TOOL_CALLS
        )

    @property
    def can_iterate(self) -> bool:
        return self.iterations < self.MAX_PLAN_VERIFY_LOOPS
